### ISSUE TITLE
Couldn't install

### ISSUE THREAD

**Issue by bioduds** [MARTIMM/mongo-perl6-driver#13] opened 2016-09-18 22:47 UTC
Hi. I did panda install MongoDB and it came back with this below, can you please help me find out what is the actual problem? tx

ubuntu@ip-172-31-47-63:~/dev/futs$ panda install MongoDB
OpenSSL provides the requested OpenSSL::Digest
URI provides the requested URI::Escape
==> MongoDB depends on Auth::SCRAM, Base64, OpenSSL
OpenSSL provides the requested OpenSSL::Digest
PKCS5 provides the requested PKCS5::PBKDF2
==> Auth::SCRAM depends on OpenSSL, Base64, PKCS5
OpenSSL provides the requested OpenSSL::Digest
==> PKCS5 depends on OpenSSL
==> Fetching OpenSSL
==> Building OpenSSL
==> Testing OpenSSL
Cannot locate native library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
  in method setup at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 306
  in method CALL-ME at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 317
  in method new at /home/ubuntu/dev/futs/.panda-work/1474229756_1/lib/OpenSSL.pm6 (OpenSSL) line 36
  in block <unit> at t/01-basic.t line 6

t/01-basic.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 9/9 subtests 
Cannot locate native library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
  in method setup at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 306
  in method CALL-ME at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 317
  in method new at /home/ubuntu/dev/futs/.panda-work/1474229756_1/lib/OpenSSL.pm6 (OpenSSL) line 36
  in sub fetch at t/02-socket.t line 24
  in block <unit> at t/02-socket.t line 6

t/02-socket.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 4/4 subtests 
Cannot locate native library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
  in method setup at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 306
  in method CALL-ME at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 317
  in method new at /home/ubuntu/dev/futs/.panda-work/1474229756_1/lib/OpenSSL/RSATools.pm6 (OpenSSL::RSATools) line 20
  in block <unit> at t/03-rsa.t line 10

t/03-rsa.t ............. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 8/8 subtests 
Cannot locate native library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
  in method setup at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 306
  in method CALL-ME at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 317
  in sub encrypt at /home/ubuntu/dev/futs/.panda-work/1474229756_1/lib/OpenSSL/CryptTools.pm6 (OpenSSL::CryptTools) line 9
  in block <unit> at t/04-crypt.t line 10
# Looks like you planned 11 tests, but ran 1

t/04-crypt.t ........... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 10/11 subtests 
Cannot locate native library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
  in method setup at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 306
  in method CALL-ME at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 317
  in sub sha1 at /home/ubuntu/dev/futs/.panda-work/1474229756_1/lib/OpenSSL/Digest.pm6 (OpenSSL::Digest) line 22
  in block <unit> at t/05-digest.t line 8

t/05-digest.t .......... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 3/3 subtests 
Cannot locate native library 'libssl.so': libssl.so: cannot open shared object file: No such file or directory
  in method setup at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 306
  in method CALL-ME at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/sources/24DD121B5B4774C04A7084827BFAD92199756E03 (NativeCall) line 317
  in method new at /home/ubuntu/dev/futs/.panda-work/1474229756_1/lib/OpenSSL.pm6 (OpenSSL) line 36
  in block <unit> at t/10-client-ca-file.t line 6

t/10-client-ca-file.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 7/7 subtests 
## Test Summary Report

t/01-basic.t         (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 9 tests but ran 0.
t/02-socket.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 4 tests but ran 0.
t/03-rsa.t           (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 8 tests but ran 0.
t/04-crypt.t         (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 11 tests but ran 1.
t/05-digest.t        (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 3 tests but ran 0.
t/10-client-ca-file.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 7 tests but ran 0.
Files=6, Tests=1, 26 wallclock secs ( 0.03 usr  0.00 sys + 24.38 cusr  1.12 csys = 25.53 CPU)
Result: FAIL
The spawned process exited unsuccessfully (exit code: 1)
  in sub run-and-gather-output at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 85
  in block  at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 22
  in sub indir at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/24811C576EF8F85E7672B26955C802BB2FC94675 (Panda::Common) line 20
  in method test at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/48E2EB9144E069353B240AD2D147B48C65F70152 (Panda::Tester) line 5
  in method install at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 156
  in block  at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 229
  in method resolve at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/sources/582CB7486602954A4601BDCE5A0EAC54B05DA58A (Panda) line 223
  in sub MAIN at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 18
  in block <unit> at /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site/resources/E0D978079BB5081DE986D058BB8AB08252F05CC8 line 151

**Comment by MARTIMM** [comment] 2016-09-19 14:10
Hi,
I see that there is a library you need, libssl.so which is needed by 
Open SSL. On fedora it seems to be in the 
openssl-devel-1.0.2h-3.fc23.x86_64 package, so look for something like 
that and try again to install.

Greetings,
Marcel

**Comment by bioduds** [comment] 2016-09-20 12:46
thanks. I need to make it work now. It installed but when I run it sends:

===SORRY!===
Could not find MongoDB::Client at line 7 in:
    /home/ubuntu/dev/futs/lib
    /home/ubuntu/.perl6
    /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site
    /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/vendor
    /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6
    CompUnit::Repository::AbsolutePath<63896064>
    CompUnit::Repository::NQP<63796680>
    CompUnit::Repository::Perl5<63796720>


On Mon, Sep 19, 2016 at 11:10 AM, Marcel Timmerman <notifications@github.com

**Comment by bioduds** [comment] 2016-09-20 12:47
testing code is:


#!/usr/bin/env perl6
use v6;
use lib 'lib';
use Futs;
use Test;
use BSON::Document;
use MongoDB::Client;
use MongoDB::Database;
use MongoDB::Collection;

my MongoDB::Client $client .= new(:uri('mongodb://127.0.0.1:3001'));
my MongoDB::Database $database = $client.database('meteor');
###
say "WELCOME TO FUTSssssss....";
my $marcelo-oliveira = Futs::Técnico.new( nome => "Marcelo Oliveira",
gênero => "Homem" );
my $fulano-do-flamengo = Futs::Técnico.new( nome => "Fulano do Flamengo",
gênero => "Mulher" );
my @técnicos = $marcelo-oliveira, $fulano-do-flamengo;
my $atlético = Futs::Time.new( nome => "Clube Atlético Mineiro", técnico =>
$marcelo-oliveira );
my $palmeiras = Futs::Time.new( nome => "Clube de Regatas Flamengo",
técnico => $fulano-do-flamengo );
my @times-do-campeonato = $atlético, $palmeiras;
my $campeonato-brasileiro = Futs::Campeonato.new( nome => "Campeonato
Brasileiro", times => @times-do-campeonato );

# Inserting data
#
my BSON::Document $req .= new: (
  insert => 'famous-people',
  documents => [
    BSON::Document.new((
      text => 'Fluminense',
    )),
  ]
);

my BSON::Document $doc = $database.run-command($req);
is $doc<ok>, 1, "insert request ok";
is $doc<n>, 1, "inserted 1 document";

**Comment by MARTIMM** [comment] 2016-09-20 18:32
Hi,

> thanks. I need to make it work now. It installed but when I run it sends:
>
> ===SORRY!===
> Could not find MongoDB::Client at line 7 in:
> /home/ubuntu/dev/futs/lib
> /home/ubuntu/.perl6
> /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/site
> /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6/vendor
> /home/ubuntu/rakudo/rakudo-star-2016.07/install/share/perl6
> CompUnit::Repository::AbsolutePath<63896064>
> CompUnit::Repository::NQP<63796680>
> CompUnit::Repository::Perl5<63796720>
>
I have no experience with rakudostar and I pull the rakudo code directly 
from github. Tried to do a rakudostar installation but failed on 
installing BSON and MongoDB. This is caused by a newer version of perl6. 
For BSON I could solve it but starting a mongod server failed in one of 
the first tests. I guess that you have a month older version.

Over to manual then....
What you perhaps need to do is to see where the Mongodb modules are 
installed with panda and then see if it is in the search paths shown 
above where perl6 is looking for them. If it isn't there you might have 
to check your path variable and or the perl6lib variable.

In the mean time I will checkout the mongod problem with rakudobrew 
because someone will encounter it sooner or later.

Greetings,
Marcel

**Comment by bioduds** [comment] 2016-09-21 12:18
great. thanks. I'll do that :)

**Comment by MARTIMM** [comment] 2017-06-18 10:38
I'll close this issue because of many changes are done in perl6, MongoDB, BSON, and change of installer. If there are other problems, please open a new issue and I'll be happy to look at it.

**Closed by MARTIMM** 2017-06-18 10:38 UTC
